version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/main"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "npm"
    directory: "/packages/worker"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
