version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/main"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/worker"
    schedule:
      interval: "daily"
