name = "moonitor"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-02-16"

build.command = "npm install && npm run build"
build.upload.format = "modules"
build.upload.main = "./worker.mjs"
kv_namespaces = [
  { binding = "KV_BOT_STORAGE", id = "f41b1157343949e3a82c48dd14a63d9b" }
]
