name: npm publish

on:
  release:
    types: [created]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: publish github package
        uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: https://npm.pkg.github.com
        run: |
          npm install
          npm run build
          npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: publish npm package
        uses: actions/setup-node@v3
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
