name: npm publish

on:
  release:
    types: [created]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: publish github package
        with:
          node-version: latest
          registry-url: https://npm.pkg.github.com
      - run: npm install
      - run: npm run build
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
      - name: publish npm package
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
